version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - test-network
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
